packages:
  - packages/**
  - docs
  - demo/*
  - e2e/**
  - test

catalog:
  '@better-auth/utils': 0.3.0
  '@better-fetch/fetch': 1.1.21
  better-call: 1.1.7
  tsdown: ^0.18.4
  typescript: ^5.9.3

catalogs:
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.3
    react-dom: ^19.2.3
  tailwind:
    '@tailwindcss/postcss': ^4.1.18
    '@tailwindcss/vite': ^4.1.18
    tailwindcss: ^4.1.18
    tailwindcss-animate: ^1.0.7
  vitest:
    '@vitest/coverage-v8': ^4.0.16
    vitest: ^4.0.16

neverBuiltDependencies: []
